### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by stuaxo** [TomOnTime/timetravelpdb#1]
Hi,
    Any chance of having a quick example in the readme of
- how to install
- how to use with someprogram.py 

?

Cheers
S

**Comment by stuaxo** [comment]
Bugger !

Here I am again, wanting something like this - time travel debugging is certainly useful.


It would be handy if this was on pypi ... and even more handy if there were an addon to ipdb that implemented this.

**Comment by TomOnTime** [comment]
Thanks for the compliment but this was just a fun little demo.  I no longer use Python, so getting this into pypi or integrating into Python 3.x is far beyond my expertise. 

timetravelpdb.py is a copy of pdb.py from the python 2.7 release, with changes.  Make sure it is in your path and use it like one would use pdb.py.  I doubt it works with 3.x but porting it shouldn't be too difficult.  I'd be glad to answer any questions.

Best,
Tom

**Comment by stuaxo** [comment]
Thanks, next time I get the urge for some time travel-debugging and land here I shall give it a go.
